options:
  debug:
    default: False
    type: boolean
    description: Enable debug logging
  fqdn:
    default:
    type: string
    description: "Fully-Qualified Domain Name of server to register"
  listen_address:
    default:
    type: string
    description: |
      Override published listen address, for example with a floating IP
  contact-email:
    default:
    type: string
    description: "Contact email for Let's Encrypt"