options:
  debug:
    default: False
    type: boolean
    description: Enable debug logging
  gerrit-directory:
    default: "/opt/gerrit"
    type: string
    description: Location for the Gerrit installation
  fqdn:
    default:
    type: string
    description: "Fully-Qualified Domain Name of server to register"
  contact-email:
    default:
    type: string
    description: "Contact email for Let's Encrypt"
  smtp-email:
    default:
    type: string
    description: SMTP from address for Gerrit
  smtp-username:
    default:
    type: string
    description: SMTP username for Gerrit
  smtp-password:
    default:
    type: string
    description: SMTP password for Gerrit
  smtp-host:
    default:
    type: string
    description: SMTP host for Gerrit
  smtp-port:
    default: 465
    type: int
    description: SMTP port for Gerrit